<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Anna Gornyitzki, Cathy Fang, Johanna Jansen, Joy Chang, Lorretta Lu">
<meta name="dcterms.date" content="2025-10-19">

<title>Analysis of class surveys</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="final-report_files/libs/clipboard/clipboard.min.js"></script>
<script src="final-report_files/libs/quarto-html/quarto.js"></script>
<script src="final-report_files/libs/quarto-html/popper.min.js"></script>
<script src="final-report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="final-report_files/libs/quarto-html/anchor.min.js"></script>
<link href="final-report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="final-report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="final-report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="final-report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="final-report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis of class surveys</h1>
<p class="subtitle lead">Which courses are most strongly associated with higher programming comfort among students?</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Anna Gornyitzki, Cathy Fang, Johanna Jansen, Joy Chang, Lorretta Lu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Updated</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 19, 2025</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="executive-summary" class="level2">
<h2 class="anchored" data-anchor-id="executive-summary">Executive summary</h2>
<p>In this project, certain university courses were examined to see how closely associated they are with the students’ comfort in programming of PSTAT197A. Using survey data from 60 students, the relationship between programming comfort levels (rated 1-5) and course enrollment across several departments was analyzed.</p>
<p>Joy’s portion of the analysis used random forest models to identify and rank the courses most strongly correlated with higher programming comfort. The analysis reveals that CS16, PSTAT 160, and PSTAT 122 are the most important predictors overall. Additionally, we find that this ranking of important courses differs significantly based on a student’s prior math proficiency, which will be elaborated in the Findings section.</p>
<p>Lorretta’s and Cathy’s portion of the analysis used ordinal logistic regression to compare comfort levels between students who had taken versus not taken each course. This approach identified the top five courses that are most strongly linked to higher programming comfort. The findings of this portion of the analysis suggest that introductory computer science and advanced data science courses have the strongest positive associations with programming comfort, highlighting their potential role in improving students’ confidence and skill development.</p>
<p>Anna and Johanna used statistical correlation to link course taking to programming comfort. They reported Spearman ρ and mean differences between took and did not take, with bar charts that rank courses and mark significance. Results align with the model based findings that introductory CS and advanced data science courses show the strongest positive associations, while noting these are associations and some courses have small sample sizes.</p>
</section>
<section id="data-description" class="level2">
<h2 class="anchored" data-anchor-id="data-description">Data description</h2>
<p>The dataset background-clean.csv contains survey responses from 60 university students aimed at understanding factors associated with programming, statistical, and mathematical comfort and proficiency. Data were collected through a self-reported questionnaire that asked participants to rate their comfort and proficiency with programming, statistics, and mathematics on a five point scale, with 1 being least comfortable and 5 being most comfortable. Additional variables recorded include course enrollment indicators across several departments, most notably Computer Science, Statistics, Linguistics, and Economics. Each course variable is coded as a binary variable, with 1 having taken the course and 0 having not taken the course before. This data set allows for comparative and inferential analyses.</p>
</section>
<section id="questions-of-interest" class="level2">
<h2 class="anchored" data-anchor-id="questions-of-interest">Questions of interest</h2>
<p>The analysis aimed to identify which courses were most strongly associated with students’ comfort in programming. Specifically, we addressed the following question:</p>
<blockquote class="blockquote">
<ol type="1">
<li><em>What are the top five courses that are most correlated with higher self-reported programming comfort among students?</em></li>
<li><em>Does math proficiency influence the ranking of the importance of courses as predictors for programming comfort? (explored using a random forest model)</em></li>
</ol>
</blockquote>
</section>
<section id="findings" class="level2">
<h2 class="anchored" data-anchor-id="findings">Findings</h2>
<section id="random-forest---joy" class="level3">
<h3 class="anchored" data-anchor-id="random-forest---joy">Random Forest - Joy</h3>
<section id="rq1-overall-course-importance" class="level4">
<h4 class="anchored" data-anchor-id="rq1-overall-course-importance">RQ1: Overall Course Importance</h4>
<p>First, we fit a model using the entire dataset to identify the courses with the strongest overall association with programming comfort. The “feature importance” score from the model measures the strength of this association. The chart below shows the top 10 most important courses.</p>
<p>It is worth noting that while feature importance reveals the strength of the relationship, it does not show the direction (i.e., whether taking the course is linked to higher or lower comfort). Therefore, the top courses shown below are only the most strongly correlated with programming comfort, but they may correlate with a higher or a lower degree of programming comfort. Despite this shortcoming, the feature importance of the random forest model has an advantage in being able to measure a predictor’s importance holistically, in the context of all other predictors. Unlike a simple correlation, which assesses only the isolated, bivariate linear relationship, the random forest’s non-linear structure accounts for interaction effects. This means the importance score of a course already reflects its conditional value, or how its contribution to programming comfort changes based on the presence or absence of other courses.</p>
<p>The top courses most strongly associated with programming comfort are CS 16, PSTAT 160, PSTAT 122, PSTAT 100, and PSTAT 131, which is reasonable since all of these courses except for 160 are programming-based. It is natural that the students who have taken these courses are more or less comfortable with programming, depending on their performance in and feelings for these courses.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Course</th>
<th style="text-align: right;">Importance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">CS16</td>
<td style="text-align: right;">0.133585</td>
</tr>
<tr class="even">
<td style="text-align: left;">PSTAT160</td>
<td style="text-align: right;">0.108485</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PSTAT122</td>
<td style="text-align: right;">0.0963313</td>
</tr>
<tr class="even">
<td style="text-align: left;">PSTAT100</td>
<td style="text-align: right;">0.0855638</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PSTAT131</td>
<td style="text-align: right;">0.0854055</td>
</tr>
</tbody>
</table>
<p><img src="random_forest_course_ranking.png" class="img-fluid"></p>
</section>
<section id="rq2-the-influence-of-math-proficiency" class="level4">
<h4 class="anchored" data-anchor-id="rq2-the-influence-of-math-proficiency">RQ2: The Influence of Math Proficiency</h4>
<p>To determine if the importance of courses changes based on a student’s background, we split the dataset into three groups: those with ‘advanced’ math proficiency, those with ‘intermediate’ proficiency, and those with ‘beginner’ proficiency.</p>
<p>We then ran the Random Forest analysis separately for each group. The subgroup whose math proficiency is ‘beginner’ is too small (n=3) to perform an analysis, so only the ‘advanced’ and ‘intermediate’ groups are kept and analyzed.</p>
<p>The comparison table below clearly shows how the ranking of the importance of courses as predictors for programming comfort changes when we take math proficiency into consideration. We can observe that CS 16, PSTAT 100, PSTAT 122, and PSTAT 160 remain the strongest predictors as in the overall course importance analysis. Their rankings change slightly - for example, PSTAT 100 becomes the most strongly correlated predictor for the group with intermediate math proficiency. Additionally, PSTAT 134, PSTAT 174, and CS 9 are included as the top predictors. These changes can be explained by the different learning paths for each group. For the ‘Math Intermediate’ students, foundational courses like PSTAT 100 and CS 9 are among the top predictors, as these courses establish the statistical and programming logic. Conversely, the ‘Math Advanced’ group, which already has this foundation, is more influenced by specialized, high-level courses like PSTAT 134 and PSTAT 174, although the foundational courses like CS 16 and PSTAT 122 are still highly important to them. This suggests that for advanced students, programming comfort is driven by applying their quantitative skills to more specific problems.</p>
<table class="table">
<colgroup>
<col style="width: 8%">
<col style="width: 20%">
<col style="width: 25%">
<col style="width: 20%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Rank</th>
<th style="text-align: left;">Course (adv)</th>
<th style="text-align: right;">Importance (adv)</th>
<th style="text-align: left;">Course (int)</th>
<th style="text-align: right;">Importance (int)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">CS16</td>
<td style="text-align: right;">0.157618</td>
<td style="text-align: left;">PSTAT100</td>
<td style="text-align: right;">0.144121</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">PSTAT122</td>
<td style="text-align: right;">0.0982008</td>
<td style="text-align: left;">CS16</td>
<td style="text-align: right;">0.138668</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">PSTAT134</td>
<td style="text-align: right;">0.0944759</td>
<td style="text-align: left;">CS9</td>
<td style="text-align: right;">0.103457</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">PSTAT174</td>
<td style="text-align: right;">0.0862864</td>
<td style="text-align: left;">PSTAT122</td>
<td style="text-align: right;">0.0978085</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">PSTAT160</td>
<td style="text-align: right;">0.0859582</td>
<td style="text-align: left;">PSTAT160</td>
<td style="text-align: right;">0.0905109</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="statistical-correlation-scores---anna-and-johanna" class="level3">
<h3 class="anchored" data-anchor-id="statistical-correlation-scores---anna-and-johanna">Statistical Correlation Scores - Anna and Johanna</h3>
<p>We computed Spearman correlation, a rank-based statistic that measures how strongly two variables move together in a monotonic pattern. In this context, it shows whether students who took certain courses tend to report higher programming comfort on a scale from 1 to 5.</p>
<p>After converting each course variable into a binary indicator (1 = took, 0 = did not take), we calculated the Spearman correlation between each course and programming comfort while removing any missing responses. The correlations were sorted from highest to lowest to identify which courses were most strongly associated with higher comfort. We then visualized the results in a bar chart to highlight these relationships.</p>
<div class="cell" data-hash="final-report_cache/html/unnamed-chunk-3_ab51a7b7afad4a1724d968f1f83b7c8d">
<div class="cell-output-display">
<p><img src="final-report_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell" data-hash="final-report_cache/html/unnamed-chunk-4_86d40abdf8b8ef1eeffe9d8a97959228">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Top five courses by Spearman rho with programming comfort</caption>
<thead>
<tr class="header">
<th style="text-align: left;">course</th>
<th style="text-align: right;">spearman_rho</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">CS16</td>
<td style="text-align: right;">0.376</td>
</tr>
<tr class="even">
<td style="text-align: left;">CS130</td>
<td style="text-align: right;">0.243</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PSTAT134</td>
<td style="text-align: right;">0.238</td>
</tr>
<tr class="even">
<td style="text-align: left;">LING104</td>
<td style="text-align: right;">0.175</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LING110</td>
<td style="text-align: right;">0.175</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The results show that CS16, CS130, PSTAT134, PSTAT127, and LING111 are among the courses most positively correlated with programming comfort. This suggests that both introductory computer science courses and upper-division data science or linguistics courses may contribute to greater programming confidence. However, since correlation measures association rather than causation, these results should be interpreted as patterns rather than proof of direct influence.</p>
</section>
<section id="logistic-regression---cathy-and-lorretta" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression---cathy-and-lorretta">Logistic Regression - Cathy and Lorretta</h3>
<p>We applied the Ordinal Logistics Model, which is also called the Cumulative Link Model, using the clm function. The simple logistics regression model can only be applied to binary data. However, the response variable of programming comfort was recorded as 1 to 5. Thus, the prog.comf was treated as an ordered categorical variable with five levels.</p>
<p>This clm function estimated the log-odds of a student being in a higher comfort category rather than a lower one. The model used a logit link function and maximum-likelihood estimation to obtain coefficient estimates for each course and threshold cut-points separating the ordered categories. Positive coefficients indicated courses associated with greater odds of higher programming comfort, while negative coefficients indicate courses associated with lower comfort levels. After that, the estimates of all courses were ranked from the highest to the lowest.</p>
<div class="cell" data-hash="final-report_cache/html/unnamed-chunk-5_976fb94c2fea759ef0c00b3a165c62b0">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make sure outcome is ordered factor</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>logistics <span class="ot">&lt;-</span> logistics <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prog.comf =</span> <span class="fu">ordered</span>(prog.comf, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>)))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Use all courses (keep everything)</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>predictors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"PSTAT100"</span>,<span class="st">"PSTAT115"</span>,<span class="st">"PSTAT120"</span>,<span class="st">"PSTAT122"</span>,<span class="st">"PSTAT126"</span>,<span class="st">"PSTAT131"</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                <span class="st">"PSTAT160"</span>,<span class="st">"PSTAT174"</span>,<span class="st">"CS9"</span>,<span class="st">"CS16"</span>,<span class="st">"LING104"</span>,<span class="st">"LING110"</span>,<span class="st">"LING111"</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>                <span class="st">"CS130"</span>,<span class="st">"CS165"</span>,<span class="st">"ECON145"</span>,<span class="st">"PSTAT127"</span>,<span class="st">"PSTAT134"</span>,<span class="st">"CS5"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only outcome + predictors, drop missing rows</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>logistics <span class="ot">&lt;-</span> logistics <span class="sc">%&gt;%</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(prog.comf, <span class="fu">all_of</span>(predictors)) <span class="sc">%&gt;%</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit Ordinal Logistic Model</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>formula <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="fu">paste</span>(<span class="st">"prog.comf ~"</span>, <span class="fu">paste</span>(predictors, <span class="at">collapse =</span> <span class="st">" + "</span>)))</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>model_clm <span class="ot">&lt;-</span> <span class="fu">clm</span>(formula, <span class="at">data =</span> logistics, <span class="at">link =</span> <span class="st">"logit"</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_clm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>formula: 
prog.comf ~ PSTAT100 + PSTAT115 + PSTAT120 + PSTAT122 + PSTAT126 + PSTAT131 + PSTAT160 + PSTAT174 + CS9 + CS16 + LING104 + LING110 + LING111 + CS130 + CS165 + ECON145 + PSTAT127 + PSTAT134 + CS5
data:    logistics

 link  threshold nobs logLik AIC    niter max.grad cond.H 
 logit flexible  51   -39.92 119.84 7(0)  7.76e-12 6.5e+02

Coefficients: (2 not defined because of singularities)
         Estimate Std. Error z value Pr(&gt;|z|)    
PSTAT100  1.67441    0.84293   1.986 0.046987 *  
PSTAT115  1.39744    1.01313   1.379 0.167791    
PSTAT120  2.00222    1.42098   1.409 0.158821    
PSTAT122 -1.26229    0.89923  -1.404 0.160393    
PSTAT126 -0.29448    1.31385  -0.224 0.822652    
PSTAT131 -1.03511    0.86471  -1.197 0.231285    
PSTAT160  0.93949    0.76747   1.224 0.220898    
PSTAT174  0.02816    0.89525   0.031 0.974908    
CS9      -0.89552    0.84705  -1.057 0.290411    
CS16      3.38134    0.92453   3.657 0.000255 ***
LING104   0.73543    2.55461   0.288 0.773435    
LING110        NA         NA      NA       NA    
LING111        NA         NA      NA       NA    
CS130     1.61892    1.60306   1.010 0.312547    
CS165    -1.27023    1.80494  -0.704 0.481588    
ECON145   0.39273    1.97860   0.198 0.842662    
PSTAT127  3.17262    2.56362   1.238 0.215880    
PSTAT134  2.34159    1.47137   1.591 0.111511    
CS5      -4.88479    2.06484  -2.366 0.017996 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Threshold coefficients:
    Estimate Std. Error z value
2|3   -2.952      2.088  -1.414
3|4    1.413      1.947   0.725
4|5    4.927      2.072   2.378</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rank Step</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>coefs <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_clm)<span class="sc">$</span>coefficients</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove threshold rows like "1|2", "2|3", etc.</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>coefs <span class="ot">&lt;-</span> coefs[<span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"</span><span class="sc">\\</span><span class="st">|"</span>, <span class="fu">rownames</span>(coefs)), , drop <span class="ot">=</span> <span class="cn">FALSE</span>]</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a simple ranked table</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>ranked_courses <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Course =</span> <span class="fu">rownames</span>(coefs),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Estimate =</span> coefs[, <span class="st">"Estimate"</span>],</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">StdError =</span> coefs[, <span class="st">"Std. Error"</span>]</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort by absolute coefficient (strongest effects first)</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>ranked_courses <span class="ot">&lt;-</span> ranked_courses[<span class="fu">order</span>(ranked_courses<span class="sc">$</span>Estimate, <span class="at">decreasing =</span> <span class="cn">TRUE</span>), ]</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ranked_courses)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Course    Estimate  StdError
CS16         CS16  3.38133839 0.9245291
PSTAT127 PSTAT127  3.17262059 2.5636153
PSTAT134 PSTAT134  2.34159040 1.4713673
PSTAT120 PSTAT120  2.00222279 1.4209752
PSTAT100 PSTAT100  1.67440989 0.8429296
CS130       CS130  1.61892200 1.6030645
PSTAT115 PSTAT115  1.39744115 1.0131255
PSTAT160 PSTAT160  0.93949191 0.7674690
LING104   LING104  0.73543145 2.5546093
ECON145   ECON145  0.39273228 1.9785975
PSTAT174 PSTAT174  0.02815919 0.8952535
PSTAT126 PSTAT126 -0.29448020 1.3138487
CS9           CS9 -0.89551792 0.8470495
PSTAT131 PSTAT131 -1.03510544 0.8647102
PSTAT122 PSTAT122 -1.26229215 0.8992269
CS165       CS165 -1.27023123 1.8049433
CS5           CS5 -4.88479278 2.0648351
LING110   LING110          NA        NA
LING111   LING111          NA        NA</code></pre>
</div>
</div>
<div class="cell" data-hash="final-report_cache/html/unnamed-chunk-6_a04641e1aecbe36c2f36805193bec05e">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Ordinal Logistic Regression Results by Course</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Course</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">StdError</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">CS16</td>
<td style="text-align: right;">3.381</td>
<td style="text-align: right;">0.925</td>
</tr>
<tr class="even">
<td style="text-align: left;">PSTAT127</td>
<td style="text-align: right;">3.173</td>
<td style="text-align: right;">2.564</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PSTAT134</td>
<td style="text-align: right;">2.342</td>
<td style="text-align: right;">1.471</td>
</tr>
<tr class="even">
<td style="text-align: left;">PSTAT120</td>
<td style="text-align: right;">2.002</td>
<td style="text-align: right;">1.421</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PSTAT100</td>
<td style="text-align: right;">1.674</td>
<td style="text-align: right;">0.843</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell" data-hash="final-report_cache/html/unnamed-chunk-7_f8948dd6e1c1ceb1b1490525ed9828d5">
<div class="cell-output-display">
<p><img src="final-report_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>According to the figure and table, the top five courses that mostly correlated to the programming comfort were CS 16, PSTAT 127, PSTAT 134, PSTAT 120, and PSTAT 100.</p>
<p>In particular, CS16 and PSTAT127 emerged as the most influential predictors with estimates of 3.381 and 3.176 respectively. It suggests that foundational computer science and data science</p>
<p>Using ordinal logistics regression, course enrollment patterns were examined to test how they may affect students’ self-reported programming comfort on a 1-5 scale. Among all courses, it appears CS 16, PSTAT 127, PSTAT 134, PSTAT 120, and PSTAT 100. This suggests that students that complete these courses are substantially more likely to report higher comfort levels in programming.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>Across random forest, ordinal logistic regression, and Spearman correlation, the results agree that introductory computer science and advanced statistics or data science courses are most strongly associated with higher programming comfort, with CS16 appearing near the top in every approach and courses such as PSTAT122, PSTAT127, PSTAT134, and PSTAT160 also showing strong positive links. Differences in exact rankings are because random forests emphasize joint predictive power and capture nonlinear interactions, ordinal logistic regression estimates each course’s directional effect while adjusting for the others, and Spearman correlation reports the simple pairwise association between a single course and comfort. Viewed together, these complementary lenses point to the same takeaway that foundational programming and applied data courses are key experiences linked to greater confidence in programming.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>